name: CI
on:
  push:
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      QDRANT_HOST: qdrant-db
      QDRANT_PORT: 6333
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: docker-compose -f compose.ci.yml build

      - name: Create Docker network
        run: docker network create ci-network || true

      - name: Run Tox tests
        run: |
          docker-compose -f compose.ci.yml up -d
          docker-compose -f compose.ci.yml run --rm bot  tox
        env:
          CI: true

      - name: Shut down services
        run: docker-compose -f compose.ci.yml down
